10 REM C64 BASIC Control Codes Demo
20 PRINT "{CLR}{LOWER}"
30 PRINT "CONTROL CODES DEMO"
40 PRINT "-------------------"
50 PRINT
60 PRINT "Screen controls:"
70 PRINT "{HOME}";"HOME";:PRINT
80 PRINT "{DOWN}";"DOWN";"  {UP}";"UP";:PRINT
90 PRINT "{LEFT}";"LEFT";"  {RIGHT}";"RIGHT";:PRINT
100 PRINT "{DEL}";"DEL  {INS}";"INS";:PRINT
110 PRINT
120 PRINT "Reverse video: {RVS}ON{RVS OFF} and {RVS}OFF{RVS OFF}"
130 PRINT
140 PRINT "Colors:" : PRINT
150 PRINT "{BLACK}";"BLACK  ";"{WHITE}";"WHITE  ";"{RED}";"RED  ";"{CYAN}";"CYAN"
160 PRINT "{PURPLE}";"PURPLE ";"{GREEN}";"GREEN ";"{BLUE}";"BLUE  ";"{YELLOW}";"YELLOW"
170 PRINT "{ORANGE}";"ORANGE ";"{BROWN}";"BROWN ";"{PINK}";"PINK  ";"{GRAY1}";"GRAY1"
180 PRINT "{GRAY2}";"GRAY2 ";"{GRAY3}";"GRAY3 ";"{LIGHTGREEN}";"LIGHTGREEN"
190 PRINT "{LIGHTBLUE}";"LIGHTBLUE"
200 PRINT
210 PRINT "Mixed text: ";"{YELLOW}";"YELLOW ";"{GREEN}";"GREEN ";"{BLUE}";"BLUE";"{WHITE}"
220 PRINT
230 PRINT
240 PRINT "{UPPER}";"Press any key...";
245 A$="":IF A$="" THEN GET A$:IF A$="" THEN 245
250 PRINT "{CLR}";"DONE"
260 END

